version: '3.8'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talenvo-api
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-talenvo}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-devkey}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-24h}
    volumes:
      - .:/app:delegated
      - /app/node_modules
      - ./temp-uploads:/app/temp-uploads:delegated
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:5000/api',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  db:
    image: postgres:15-alpine
    container_name: talenvo-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-talenvo}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-talenvo}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    name: talenvo-postgres-data
